In [363]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn

In [364]:
path="/Users/jeya/Desktop/ML/Real estate.csv"
data=pd.read_csv(path)
data.head()

No  X1 transaction date  X2 house age  \
0   1             2012.917          32.0   
1   2             2012.917          19.5   
2   3             2013.583          13.3   
3   4             2013.500          13.3   
4   5             2012.833           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [365]:
data_numpy=data.values
data_numpy

array([[1.0000000e+00, 2.0129170e+03, 3.2000000e+01, ..., 2.4982980e+01,
        1.2154024e+02, 3.7900000e+01],
       [2.0000000e+00, 2.0129170e+03, 1.9500000e+01, ..., 2.4980340e+01,
        1.2153951e+02, 4.2200000e+01],
       [3.0000000e+00, 2.0135830e+03, 1.3300000e+01, ..., 2.4987460e+01,
        1.2154391e+02, 4.7300000e+01],
       ...,
       [4.1200000e+02, 2.0132500e+03, 1.8800000e+01, ..., 2.4979230e+01,
        1.2153986e+02, 4.0600000e+01],
       [4.1300000e+02, 2.0130000e+03, 8.1000000e+00, ..., 2.4966740e+01,
        1.2154067e+02, 5.2500000e+01],
       [4.1400000e+02, 2.0135000e+03, 6.5000000e+00, ..., 2.4974330e+01,
        1.2154310e+02, 6.3900000e+01]])

In [366]:
data_tensor=torch.from_numpy(data_numpy)
print(data_tensor.dtype)
data_tensor=data_tensor.to(torch.float32)
print(data_tensor.dtype)

torch.float64
torch.float32


In [367]:
inputs=data_tensor[:,1:-1]
print(inputs.shape)
inputs

torch.Size([414, 6])


tensor([[2012.9170,   32.0000,   84.8788,   10.0000,   24.9830,  121.5402],
        [2012.9170,   19.5000,  306.5947,    9.0000,   24.9803,  121.5395],
        [2013.5830,   13.3000,  561.9845,    5.0000,   24.9875,  121.5439],
        ...,
        [2013.2500,   18.8000,  390.9696,    7.0000,   24.9792,  121.5399],
        [2013.0000,    8.1000,  104.8101,    5.0000,   24.9667,  121.5407],
        [2013.5000,    6.5000,   90.4561,    9.0000,   24.9743,  121.5431]])

In [368]:
targets=data_tensor[:,-1]
print(targets.shape)
targets=targets.unsqueeze_(1)
print(targets.shape)

torch.Size([414])
torch.Size([414, 1])


In [369]:
from torch.utils.data import TensorDataset
tensor_ds=TensorDataset(inputs,targets)
tensor_ds[:9]

(tensor([[2.0129e+03, 3.2000e+01, 8.4879e+01, 1.0000e+01, 2.4983e+01, 1.2154e+02],
         [2.0129e+03, 1.9500e+01, 3.0659e+02, 9.0000e+00, 2.4980e+01, 1.2154e+02],
         [2.0136e+03, 1.3300e+01, 5.6198e+02, 5.0000e+00, 2.4987e+01, 1.2154e+02],
         [2.0135e+03, 1.3300e+01, 5.6198e+02, 5.0000e+00, 2.4987e+01, 1.2154e+02],
         [2.0128e+03, 5.0000e+00, 3.9057e+02, 5.0000e+00, 2.4979e+01, 1.2154e+02],
         [2.0127e+03, 7.1000e+00, 2.1750e+03, 3.0000e+00, 2.4963e+01, 1.2151e+02],
         [2.0127e+03, 3.4500e+01, 6.2347e+02, 7.0000e+00, 2.4979e+01, 1.2154e+02],
         [2.0134e+03, 2.0300e+01, 2.8760e+02, 6.0000e+00, 2.4980e+01, 1.2154e+02],
         [2.0135e+03, 3.1700e+01, 5.5120e+03, 1.0000e+00, 2.4951e+01, 1.2148e+02]]),
 tensor([[37.9000],
         [42.2000],
         [47.3000],
         [54.8000],
         [43.1000],
         [32.1000],
         [40.3000],
         [46.7000],
         [18.8000]]))

In [370]:
from torch.utils.data import DataLoader
batch_size=20
trian_loader=DataLoader(tensor_ds,batch_size,shuffle=True)

In [371]:
for xb,yb in trian_loader:
    print(xb)
    print(yb)
    break

tensor([[2.0127e+03, 5.6000e+00, 9.0456e+01, 9.0000e+00, 2.4974e+01, 1.2154e+02],
        [2.0128e+03, 1.8400e+01, 2.6750e+03, 3.0000e+00, 2.4961e+01, 1.2151e+02],
        [2.0135e+03, 1.3300e+01, 5.6198e+02, 5.0000e+00, 2.4987e+01, 1.2154e+02],
        [2.0128e+03, 5.9000e+00, 9.0456e+01, 9.0000e+00, 2.4974e+01, 1.2154e+02],
        [2.0136e+03, 3.5700e+01, 5.7921e+02, 2.0000e+00, 2.4982e+01, 1.2155e+02],
        [2.0133e+03, 1.3900e+01, 2.8932e+02, 5.0000e+00, 2.4982e+01, 1.2154e+02],
        [2.0131e+03, 4.1300e+01, 4.0188e+02, 4.0000e+00, 2.4983e+01, 1.2154e+02],
        [2.0129e+03, 1.5900e+01, 2.8932e+02, 5.0000e+00, 2.4982e+01, 1.2154e+02],
        [2.0129e+03, 2.7100e+01, 4.4128e+03, 1.0000e+00, 2.4950e+01, 1.2150e+02],
        [2.0128e+03, 1.8000e+00, 1.4558e+03, 1.0000e+00, 2.4951e+01, 1.2155e+02],
        [2.0132e+03, 1.6200e+01, 2.8932e+02, 5.0000e+00, 2.4982e+01, 1.2154e+02],
        [2.0133e+03, 1.6700e+01, 4.0820e+03, 0.0000e+00, 2.4942e+01, 1.2150e+02],
        [2.0129e

In [372]:
model=nn.Linear(6,1)
print(model.weight)
print(model.bias)
list(model.parameters())

Parameter containing:
tensor([[ 0.2181, -0.2364,  0.0805,  0.2447,  0.1978,  0.3174]],
       requires_grad=True)
Parameter containing:
tensor([0.0516], requires_grad=True)


[Parameter containing:
 tensor([[ 0.2181, -0.2364,  0.0805,  0.2447,  0.1978,  0.3174]],
        requires_grad=True),
 Parameter containing:
 tensor([0.0516], requires_grad=True)]

In [373]:
preds=model(inputs)
preds

tensor([[ 484.2671],
        [ 504.8183],
        [ 526.0048],
        [ 525.9866],
        [ 514.0067],
        [ 656.5722],
        [ 526.2276],
        [ 502.4765],
        [ 918.9762],
        [ 622.6514],
        [ 507.2130],
        [ 490.6358],
        [ 520.3107],
        [ 677.3806],
        [ 574.2764],
        [ 521.3616],
        [ 507.6727],
        [ 506.8073],
        [ 510.2486],
        [ 485.7361],
        [ 665.4653],
        [ 504.3593],
        [ 588.7736],
        [ 504.3810],
        [ 512.8706],
        [ 595.8770],
        [ 513.8807],
        [ 503.6320],
        [ 523.9802],
        [ 518.4482],
        [ 840.2485],
        [ 539.1472],
        [ 513.1160],
        [ 506.2393],
        [ 497.1171],
        [ 807.6754],
        [ 635.2712],
        [ 589.4664],
        [ 529.7444],
        [ 503.2856],
        [ 807.8271],
        [ 805.9385],
        [ 517.1505],
        [ 517.1211],
        [ 525.9700],
        [ 515.2316],
        [ 517.0707],
        [ 526

In [374]:
import torch.nn.functional as f
loss_fn=f.mse_loss
loss=loss_fn(preds,targets)
loss.data

tensor(291689.1250)

In [375]:
opt=torch.optim.SGD(model.parameters(),1e-9)

In [376]:
def fit(num_epochs):
    for epochs in range(num_epochs):
        for xb,yb in trian_loader:
            preds=model(xb)
            loss=loss_fn(preds,yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if (epochs+1)%10==0:
            print("current epoch/number of epochs [{}]/[{}],loss : {}".format(epochs+1,num_epochs,loss))

In [377]:
fit(100)

current epoch/number of epochs [10]/[100],loss : 3766.205810546875
current epoch/number of epochs [20]/[100],loss : 930.9207763671875
current epoch/number of epochs [30]/[100],loss : 572.4326171875
current epoch/number of epochs [40]/[100],loss : 106.03307342529297
current epoch/number of epochs [50]/[100],loss : 83.80718231201172
current epoch/number of epochs [60]/[100],loss : 165.60902404785156
current epoch/number of epochs [70]/[100],loss : 549.2859497070312
current epoch/number of epochs [80]/[100],loss : 89.83628845214844
current epoch/number of epochs [90]/[100],loss : 67.8929672241211
current epoch/number of epochs [100]/[100],loss : 32.300941467285156


In [378]:
preds

tensor([[ 484.2671],
        [ 504.8183],
        [ 526.0048],
        [ 525.9866],
        [ 514.0067],
        [ 656.5722],
        [ 526.2276],
        [ 502.4765],
        [ 918.9762],
        [ 622.6514],
        [ 507.2130],
        [ 490.6358],
        [ 520.3107],
        [ 677.3806],
        [ 574.2764],
        [ 521.3616],
        [ 507.6727],
        [ 506.8073],
        [ 510.2486],
        [ 485.7361],
        [ 665.4653],
        [ 504.3593],
        [ 588.7736],
        [ 504.3810],
        [ 512.8706],
        [ 595.8770],
        [ 513.8807],
        [ 503.6320],
        [ 523.9802],
        [ 518.4482],
        [ 840.2485],
        [ 539.1472],
        [ 513.1160],
        [ 506.2393],
        [ 497.1171],
        [ 807.6754],
        [ 635.2712],
        [ 589.4664],
        [ 529.7444],
        [ 503.2856],
        [ 807.8271],
        [ 805.9385],
        [ 517.1505],
        [ 517.1211],
        [ 525.9700],
        [ 515.2316],
        [ 517.0707],
        [ 526

In [379]:
targets

tensor([[ 37.9000],
        [ 42.2000],
        [ 47.3000],
        [ 54.8000],
        [ 43.1000],
        [ 32.1000],
        [ 40.3000],
        [ 46.7000],
        [ 18.8000],
        [ 22.1000],
        [ 41.4000],
        [ 58.1000],
        [ 39.3000],
        [ 23.8000],
        [ 34.3000],
        [ 50.5000],
        [ 70.1000],
        [ 37.4000],
        [ 42.3000],
        [ 47.7000],
        [ 29.3000],
        [ 51.6000],
        [ 24.6000],
        [ 47.9000],
        [ 38.8000],
        [ 27.0000],
        [ 56.2000],
        [ 33.6000],
        [ 47.0000],
        [ 57.1000],
        [ 22.1000],
        [ 25.0000],
        [ 34.2000],
        [ 49.3000],
        [ 55.1000],
        [ 27.3000],
        [ 22.9000],
        [ 25.3000],
        [ 47.7000],
        [ 46.2000],
        [ 15.9000],
        [ 18.2000],
        [ 34.7000],
        [ 34.1000],
        [ 53.9000],
        [ 38.3000],
        [ 42.0000],
        [ 61.5000],
        [ 13.4000],
        [ 13.2000],


In [380]:
result=model(torch.tensor([[2012.9170,   19.5000,  306.5947,    9.0000,   24.9803,  121.5395]]))

In [383]:
result

tensor([[44.5424]], grad_fn=<AddmmBackward0>)

In [384]:
print("predicted house of unit area is {:}".format(result))

predicted house of unit area is tensor([[44.5424]], grad_fn=<AddmmBackward0>)
